language: c
compiler:
  - gcc
  - clang

# Use a container Travis
sudo: false

install:
  - ./getversion
  - autoreconf -i -I m4

script: ./configure && make

notifications:
  irc: "irc.oftc.net#munin"

# Travis -> Coverity
env:
  global:
    - secure: "CNXrpwGgWHhD9894gMeKqlt/5eeKJ+J764jRV685JWV/5OrHeWqEfAp+onX/B+RUCl5DrFpblyQl2K6IDTABolkY4Vy/kvZHB5Y2XhyXu3U6RzQwdH3xo9olJQ+UcGzNOc1YOqSWzkDG2JbR9HthgyWgMjbvePXn5AKRGUTAasI="

addons:
  coverity_scan:
    project:
      name: munin-monitoring/munin-c
      version: 0.0.9
      description: Munin node

    notification_email: ssm@fnord.no
    build_command_prepend: ./configure
    build_command: make
    branch_pattern: coverity_scan
